### ISSUE TITLE
identification of the explicit CAS login or logout

### ISSUE THREAD

**Issue by uidev547** [AceMetrix/connect-cas#37]
Hi,

Does connect-cas will identify if the user explicitly logged in or logged out the CAS server without using node application? 

Thanks
Kiran

**Comment by badunk** [comment]
I'm not sure what you mean

CAS does not deal with user sessions, so it doesn't actually have the information of whether a user is still logged in or not.  I believe all of information the CAS server has on the user is very short-lived, expecting tickets to be redeemed within seconds before invalidating them.

The session exists on the CAS client (connect-cas in this case).

Can you clarify what you're trying to do?

**Comment by uidev547** [comment]
Hi @badunk 

Application scenario:
When user accessing node application ( exampleurl : www.nodeapplication.com/ ) which is using connect-cas  if user is already logged in CAS ( exampleurlurl: www.examplesite.com/cas/login ) then page should show Authenticated view, Otherwise Unauthenticated view.

And if the user logged out from the CAS ( exampleurl: www.examplesite.com/cas/logout ) then user again trying to access the node application then user should see unauthenticated view.

As for i understand connect-cas module will identify the user once for the browser session. 

Thanks
Kiran

**Comment by badunk** [comment]
Ah sorry, its been a while since I looked at the protocol.

This is true, the CAS server with single sign on will provide a CASTGC containing the TGT.  This cookie is how CAS knows you're authenticated.  This, however, is outside of connect-cas and is the responsibility of the CAS server.

When attempting to login into www.nodeapplication.com for the first time (for example), it will find that there was no service ticket provided by CAS and no existing user session.  From that, it will provide a 302 redirect to your cas instance (www.examplesite.com/cas/login) with the unauthenticated view.

After authenticating, the CAS server will redirect the user back to the node application and provide a one-time use service ticket.  This time around, connect-cas sees there is a service ticket provided and checks with the configured CAS server of whether the user is who they say they are.  If so, an application-specific session is established and the user may proceed.

Subsequent requests to the node application will be authenticated due to this session established with the node app.  When that session finally expires, the logic repeats itself and redirects them to the login screen.

At that point, if somehow the TGT that CAS initially provided you still has not expired, then CAS should be configured to automatically give you a new service ticket for your node app.  This all happens via browser redirects.

http://jasig.github.io/cas/4.0.x/protocol/CAS-Protocol.html

Does that answer your question?  The node application does not really know how your CAS session TTL - I don't believe its supposed to.  It establishes its own session with you.

**Comment by uidev547** [comment]
Yes @badunk.

But some pages of node application is having the sensitive information which should not be accessed after logged out in CAS server. If user In CAS server logged out then also node application is having the user session and able to access all the pages. I'll go through the node module code and verify if it can help me in this scenario.

Thanks a lot @badunk

**Comment by badunk** [comment]
Ah I see what you're asking about now.

Yes, that is CAS's single sign out feature, and there is some support of that.  https://wiki.jasig.org/display/casum/single+sign+out

The protocol is such that when you sign out of CAS, CAS is supposed to send a request to registered clients (like connect-cas).  The expectation is that the node application will automatically expire your session.

See https://github.com/AceMetrix/connect-cas/blob/master/test/ssout.spec.js for example.  Try using it like:

```
var ssout = require('connect-cas').ssout;

app.use(ssout('/url/you/registered/with/cas/server'));
```

**Comment by uidev547** [comment]
Thanks
